### PR TITLE
another attempt

### PR DESCRIPTION
**Pull request by shajra**
Some of us feel the original writeup is too long, repetitious, and
poorly worded.

If we're going to say anything at all, it should be concise, as
straight-forward as possible, and not belabor any one point for too
long.

Otherwise, I would rather just delete this repository altogether.

That said, if this were my project, and my project alone, I might take a
different approach.  My personal value set has some congruence with
Scalaz's approach, but is not perfectly aligned.

However, I'm open to Scalaz existing by the terms that Scalaz was
founded, and have tried to keep the part of the original writeup that
matches my experience using the library and working with other people
using or contributing to it.

### CODE REVIEW

**Comment by tonymorris** [comment]
Looks good.

> which many suspect was designed expressly to eject a specific member

There are no suspicions. There is conclusive evidence. Has been for years.

**Comment by tonymorris** [comment]
Please do not use aggression as a pejorative. There is nothing wrong with aggression, just like many other personal traits that have a useful practical application.

I think it is best to not discuss "insult", etc. While it definitely is not defined, based on repeated failed attempts to do so, subscription to the pseudo-idea is typically used a form pf psychological abuse.

* You cause me to be insulted.
* You cause me to punch my hand into your face.

I am not sure why ad hominem fallacies are mentioned. Ad hominems are quite rare, almost non-existent.

**Comment by shajra** [comment]
I agree that "aggression" should not be considered a pejorative.  I have the idea to replace that word with "bullying," which is really my intent.  That's a small change.

@vmarquez has a quick review of this shortly before my PR as a sanity check, and he had some interest in being clear on ad hominem attacks.  I thought it was fine to include, if only as another example of recommended interaction.  But that section was not there before, and could be removed.

> I think it is best to not discuss "insult", etc.

I believe I try to make exactly the point you bring up.  Removing all reference to "insult" would pull at the strings of other comments that are tied to it, which I believe are worth keeping.

Maybe we're not too far off.  I'll push the simple change from "aggression" to "bullying."

**Comment by vmarquez** [comment]
👍

**Comment by tonymorris** [comment]
I am much less concerned with detailing the intricacies of the meaning of the word "insult" and how it is used in practice, than I am in restoring the mode of operation of Scalaz pre-2013, then putting in place measures to prevent the destruction by malicious agents. This is primary. The rest is just ranting.

**Comment by vmarquez** [comment]
as my colleagues would say, 'let's ship it'.  Can we merge?  We can add to it as we go.

**Review by S11001001 — APPROVED** [review]
Concision is equivalent to preciseness.

**Comment by shajra** [comment]
I wanted to sleep on it.  I just made a few edits after reviewing it.  I'm out of ideas on how to improve it further.

Regarding concision, I'm glad we're all in agreement.  It's certainly more concise than it was before.  I think @tonymorris may have ideas on how to shrink it further (his comment above about "insult" and "rest is just ranting."  Maybe that's a good idea, but I might not be the best one to do it; I feel spent in this effort.

Also, I'm fine if it's not so concise as to lose its conversational flow.

**Comment by tonymorris** [comment]
I'm remaining ambivalent.

**Pull request merged**
